### ISSUE TITLE
How should i use the interface lv.img.set_src

### ISSUE THREAD

**Issue by zhenpengliang555** [littlevgl/lv_binding_micropython#51]
here is my code
scr7=lv.obj()
img1=lv.img()
lv.img.set_src(img1,lv.SYMBOL.OK)

then,i got a error:
SyntaxError: Cannot convert str to pointer!

The corresponding C examples is as follows:
1
 lv_obj_t * img2 = lv_img_create(lv_scr_act(), NULL);
    lv_img_set_src(img2, LV_SYMBOL_OK "Accept");
2
lv_obj_t * img1 = lv_img_create(lv_scr_act(), NULL);
    lv_img_set_src(img1, &cogwheel);

But,How should i use the interface lv.img.set_src？What type should the second parameter be？

**Comment by amirgon** [comment]
Hi @zhenpengliang555 

Next time, **please ask questions in the [forum](https://forum.littlevgl.com)** instead of opening a github issue.

You need to call the `set_src` method of the image object, not of the image class.

For example:
```python
img = lv.img(lv.scr_act())
img.set_src(lv.SYMBOL.OK)
```

[demo](https://littlevgl.github.io/lv_micropython/ports/javascript/lvgl_editor.html?script_direct=50dd59e91909a86af9d4dc12827f513db5ddd69a)
